whogivesmore/config/routes.rb
Rails.application.routes.draw do


  get 'mains/index'

  get 'mains/show'

  # get 'account_informations/index'

  # get 'account_informations/edit'

  # get 'account_informations/new'

  # get 'account_informations/show'

  # get 'donations/index'

  # get 'donations/new'

  # get 'donations/show'

  # get 'donations/edit'

  # get 'charties/index'

  # get 'charties/new'

  # get 'charties/show'

  # get 'charties/edit'

  # get 'competitions/index'

  # get 'competitions/show'

  # get 'competitions/edit'

  # get 'competitions/new'

  # get 'teams/index'

  # get 'teams/new'

  # get 'teams/show'

  # get 'teams/edit'

  # mount_devise_token_auth_for 'User', at: 'auth'
  
  # resources :users
  resources :teams
  resources :competitions
  resources :charties
  resources :donations
  resources :baskets

  # root 'home#index'
  resources :account_informations
  # devise_for :users

 devise_for :users, controllers: {
        sessions: 'users/sessions',       
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      } 
# as:user do
# devise_for :users, skip: [:registrations]
# as :user do
#   # get 'signin', to: 'devise/sessions#new', as: :new_user_session
#   # post 'signin', to: 'devise/sessions#create', as: :user_session

#   get 'sign_up',to: 'devise/registrations#new' ,as: :new_user_registration
#   get 'users/:id/edit',to: 'devise/registrations#edit', as: :edit_user_registration
#  patch 'users/:id',to: 'devise/registrations#update', as: :update_user_registration
#  put 'users/:id',to: 'devise/registrations#update'
#  delete 'users/:id',to: 'devise/registrations#destroy', as: :destroy_user_registration

#   # match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
# end
      
# devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #  namespace :users, :defaults => {:format => :json} do
  #   as :user do
  #     post   "/sign-in"       => "sessions#create"
  #     delete "/sign-out"      => "sessions#destroy"
  #   end
  # end
end

whogivesmore/app/models/donation.rb
class Donation < ApplicationRecord
  validates :firstname_on_card,:lastname_on_card,:expiration_date,:billing_address,:amount ,:presence => true
  validates :card_number ,:presence => true,
                          :length=> {:is=>16}
                          # :uniqueness => true
  validates :cvv ,:presence => true,
                :uniqueness=>true,
                :length => {:is => 3 }
end

whogivesmore/app/controllers/donations_controller.rb
class DonationsController < ApplicationController
   before_action :set_donation, only: [:show, :edit, :update, :destroy]
# skip_before_action :require_login?

  def index
    @donations =Donation.all
     @highest_donor=Donation.order('amount DESC').limit(3)
  end

  def show
  end

  def new
    @donation = Donation.new
  end
  
  def edit
  end
  
  def create
    @donation = Donation.new(donation_params)
    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render json:{ status: :ok, data: @donation }   }
      else
        format.html { render :new }
        format.json { render json:{ status: :error, data: @donation.errors } }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'donation was successfully updated.' }
        format.json { render json:{status: :ok, data: @donation}  }
      else
        format.html { render :edit }
        format.json { render json:{status: :error,data: @donation.errors }}
      end
    end
  end

 
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'donation was successfully destroyed.' }
      format.json { render json:{status: :delete }}
    end
  end

  private
    def set_donation
       @donation = Donation.where("id=?",params[:id]).first
      unless @donation.present? 
        render json:{ status: :error, data: "donation is not find" }
      end
    end
    def donation_params
      params.require(:donation).permit(:firstname_on_card,:lastname_on_card,:card_number,:expiration_date,:cvv,:billing_address,:amount,:user_id,:team_id)
    end
end

whogivesmore/app/helpers/donations_helper.rb
module DonationsHelper
end

whogivesmore/app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
<div class="field">
    <%= f.label :firstname_on_card %>
    <%= f.text_field :firstname_on_card %>
  </div>
<div class="field">
    <%= f.label :lastname_on_card %>
    <%= f.text_field :lastname_on_card %>
  </div>
  <div class="field">
    <%= f.label :card_number %>
    <%= f.number_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.date_field :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :cvv %>
    <%= f.number_field :cvv %>
  </div>
  <div class="field">
    <%= f.label :billing_address %>
    <%= f.text_field :billing_address %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :team_id %>
    <%= f.number_field :team_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

whogivesmore/app/views/donations/edit.html.erb
<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @donation %> |
  <%= link_to "View All", donations_path %>
</p>

whogivesmore/app/views/donations/index.html.erb
<table>
  <thead>
    <tr>
      <th>Firstname_on_card</th>
      <th>Lastname_on_card</th>
      <th>card_number</th>
      <th>expiration_date</th>
      <th>cvv</th>
      <th>billing_address</th>
      <th>user_id</th>
      <th>team_id</th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.firstname_on_card %></td>
          <td><%= donation.lastname_on_card %></td>
          <td><%= donation.card_number %>
          <td><%= donation.expiration_date %>
          <td><%= donation.cvv %>
          <td><%= donation.billing_address %>
          <td><%= donation.user_id%>
          <td><%= donation.team_id %>
        <td><%= link_to 'Show',donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New donation', new_donation_path %>

whogivesmore/app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Back', donations_path %>

whogivesmore/app/views/donations/show.html.erb
<p>
  <strong>FirstName_on_card:</strong>
  <%=h @donation.firstname_on_card%>
</p>
<p>
  <strong>LastName_on_card:</strong>
  <%=h @donation.lastname_on_card%>
</p>
<p>
  <strong>card_number</strong>
  <%=h @donation.card_number %>
</p>
<p>
  <strong>Expiration_on_date:</strong>
  <%=h @donation.expiration_date%>
</p>
<p>
  <strong>CVV:</strong>
  <%=h @donation.cvv%>
</p>
<p>
  <strong>billing_address:</strong>
  <%=h @donation.billing_address%>
</p>
<p>
  <strong>Amount</strong>
  <%=h @donation.amount%>
</p>
<p>
  <strong>User_id:</strong>
  <%=h @donation.user_id%>
</p>
<p>
  <strong>Team_id</strong>
  <%=h @donation.team_id%>
</p>
<p>
  <%= link_to "Edit", edit_donation_path(@donation) %> |
  <%= link_to "Destroy", @donation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", donations_path %>
</p>