whogivesmore/config/routes.rb
Rails.application.routes.draw do


  get 'mains/index'

  get 'mains/show'

  # get 'account_informations/index'

  # get 'account_informations/edit'

  # get 'account_informations/new'

  # get 'account_informations/show'

  # get 'donations/index'

  # get 'donations/new'

  # get 'donations/show'

  # get 'donations/edit'

  # get 'charties/index'

  # get 'charties/new'

  # get 'charties/show'

  # get 'charties/edit'

  # get 'competitions/index'

  # get 'competitions/show'

  # get 'competitions/edit'

  # get 'competitions/new'

  # get 'teams/index'

  # get 'teams/new'

  # get 'teams/show'

  # get 'teams/edit'

  # mount_devise_token_auth_for 'User', at: 'auth'
  
  # resources :users
  resources :teams
  resources :competitions
  resources :charties
  resources :donations
  resources :baskets

  # root 'home#index'
  resources :account_informations
  # devise_for :users

 devise_for :users, controllers: {
        sessions: 'users/sessions',       
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      } 
# as:user do
# devise_for :users, skip: [:registrations]
# as :user do
#   # get 'signin', to: 'devise/sessions#new', as: :new_user_session
#   # post 'signin', to: 'devise/sessions#create', as: :user_session

#   get 'sign_up',to: 'devise/registrations#new' ,as: :new_user_registration
#   get 'users/:id/edit',to: 'devise/registrations#edit', as: :edit_user_registration
#  patch 'users/:id',to: 'devise/registrations#update', as: :update_user_registration
#  put 'users/:id',to: 'devise/registrations#update'
#  delete 'users/:id',to: 'devise/registrations#destroy', as: :destroy_user_registration

#   # match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
# end
      
# devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #  namespace :users, :defaults => {:format => :json} do
  #   as :user do
  #     post   "/sign-in"       => "sessions#create"
  #     delete "/sign-out"      => "sessions#destroy"
  #   end
  # end
end

whogivesmore/app/models/basket.rb
class Basket < ApplicationRecord
   
  validates :name ,:presence=>true
  has_many :user_baskets
  has_many :users, through: :user_baskets 
  has_one :picture ,as: :imageable
  accepts_nested_attributes_for :picture
end

whogivesmore/app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :require_login?
  before_action :set_basket, only: [:show, :edit, :update, :destroy]
# before_action :authenticate
  # skip_before_action :require_login?

  def index
    @baskets =Basket.all
    @pictures=Picture.all
    #@picture=@basket.pictures
  end

  def show
   @picture=@basket.picture
  end
 
  def new
    @basket = Basket.new
    @basket.build_picture
  end
  
  def edit
  end
  
  def create
    @basket = Basket.new(basket_params)
    # binding.pry
      respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'basket was successfully created.' }
        format.json {  render json:{status: :ok,data: @basket } }
      else
        format.html { render :new }
        format.json { render json:{status: :error,data: @basket.errors }}
      end
    end
  end
 
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'basket was successfully updated.' }
        format.json { render :show, status: :ok, data: @basket ,location: @basket}
      else
        format.html { render :edit }
        format.json { render json:{ status: :error,data: @basket.errors } }
      end
    end
  end
 
  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'basket was successfully destroyed.' }
      format.json { render json:{status: :delete }}
    end
  end

  private
    def set_basket
      @basket = Basket.where("id=?",params[:id]).first

      unless @basket.present? 
        render json:{ status: :error, data: "basket is not find" }

      end
    end

    def basket_params
      params.require(:basket).permit(:name,:custom,
        :percentage,picture_attributes: [:avatar])
    end
end

whogivesmore/app/helpers/baskets_helper.rb
module BasketsHelper
end

whogivesmore/app/views/baskets/_form.html.erb
<%= form_for(@basket) do |f| %>

<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :custom %>
    <%= f.check_box :custom %>
  </div>
  <div class="field">

  <%= f.label :picture %>
    <%= f.fields_for :picture do |photo| %>
    <%= photo.file_field :avatar %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

whogivesmore/app/views/baskets/edit.html.erb
<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @basket %> |
  <%= link_to "View All", baskets_path %>
</p>

whogivesmore/app/views/baskets/index.html.erb
<%= link_to 'New Basket', new_basket_path %>
<table>
  <thead>
    <tr>
      <th>picture</th>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <% @pictures.each do |pic| %>
        <% if (pic.imageable_type=="Basket") %>
        <% if(pic.imageable_id==basket.id) %>
        <td><%= image_tag(pic.avatar)%></td>
        <% end %>
        <% end %>
        <% end %>
          <td><%= basket.name %></td>
          <td><%= basket.custom %>
        <td><%= link_to 'Show',basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

whogivesmore/app/views/baskets/new.html.erb
<%= render 'form', basket: @basket %>

<%= link_to 'Back', baskets_path %>

whogivesmore/app/views/baskets/show.html.erb
<p>
  <strong>Name:</strong>

   <% if(@picture.imageable_id==@basket.id) %>
        <%= image_tag(@picture.avatar)%>
 
  <% end %>
</p>
<p>
  <strong>Name:</strong>
  <%=h @basket.name %>
</p>

<p>
  <strong>Name:</strong>
  <%=h @basket.custom %>
</p>




<p>
  <%= link_to "Edit", edit_basket_path(@basket) %> |
  <%= link_to "Destroy", @basket, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", baskets_path %>
</p>