whogivesmore/config/routes.rb
Rails.application.routes.draw do


  get 'mains/index'

  get 'mains/show'

  # get 'account_informations/index'

  # get 'account_informations/edit'

  # get 'account_informations/new'

  # get 'account_informations/show'

  # get 'donations/index'

  # get 'donations/new'

  # get 'donations/show'

  # get 'donations/edit'

  # get 'charties/index'

  # get 'charties/new'

  # get 'charties/show'

  # get 'charties/edit'

  # get 'competitions/index'

  # get 'competitions/show'

  # get 'competitions/edit'

  # get 'competitions/new'

  # get 'teams/index'

  # get 'teams/new'

  # get 'teams/show'

  # get 'teams/edit'

  # mount_devise_token_auth_for 'User', at: 'auth'
  
  # resources :users
  resources :teams
  resources :competitions
  resources :charties
  resources :donations
  resources :baskets

  # root 'home#index'
  resources :account_informations
  # devise_for :users

 devise_for :users, controllers: {
        sessions: 'users/sessions',       
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      } 
# as:user do
# devise_for :users, skip: [:registrations]
# as :user do
#   # get 'signin', to: 'devise/sessions#new', as: :new_user_session
#   # post 'signin', to: 'devise/sessions#create', as: :user_session

#   get 'sign_up',to: 'devise/registrations#new' ,as: :new_user_registration
#   get 'users/:id/edit',to: 'devise/registrations#edit', as: :edit_user_registration
#  patch 'users/:id',to: 'devise/registrations#update', as: :update_user_registration
#  put 'users/:id',to: 'devise/registrations#update'
#  delete 'users/:id',to: 'devise/registrations#destroy', as: :destroy_user_registration

#   # match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
# end
      
# devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #  namespace :users, :defaults => {:format => :json} do
  #   as :user do
  #     post   "/sign-in"       => "sessions#create"
  #     delete "/sign-out"      => "sessions#destroy"
  #   end
  # end
end

whogivesmore/app/models/account_information.rb
class AccountInformation < ApplicationRecord
validates :first_name,:last_name ,:presence => true

validates :zipcode ,:presence => true,
                    :length => {:is => 6 }


end

whogivesmore/app/controllers/account_informations_controller.rb
class AccountInformationsController < ApplicationController
 before_action :set_accountinfo, only: [:show, :edit, :update, :destroy]


  def index
    @accountinformations =AccountInformation.all
  end

  def show
  end
 
  def new
    @accountinformation = AccountInformation.new
  end

  def edit
  end
  
  def create
    @accountinformation = AccountInformation.new(account_params)
    respond_to do |format|
      if @accountinformation.save
        format.html { redirect_to @accountinformation, notice: 'Donation was successfully created.' }
        format.json {  render json:{status: :ok , data: @accountinformation } }
      else
        format.html { render :new }
        format.json { render json:{  status: :error,data: @accountinformation.errors,} }
      end
    end
  end
 
  def update
    respond_to do |format|
      if @accountinformation.update(account_params)
        format.html { redirect_to @accountinformation, notice: 'account was successfully updated.' }
        format.json { render :show, status: :ok, location: @accountinformation }
      else
        format.html { render :edit }
        format.json { render json: @accountinformation.errors, status: :error }
      end
    end
  end
  def destroy
    @accountinformation.destroy
    respond_to do |format|
      format.html { redirect_to account_informations_url, notice: 'account information  was successfully destroyed.' }
      format.json { render json:{status: :delete }}
    end
  end
  private
    def set_accountinfo
      @accountinformation = AccountInformation.where("id=?",params[:id]).first
      unless @accountinformation.present? 
        render json:{ status: :error, data: "accountinformation is not find" }
      end
    end

    def account_params
      params.require(:account_information).permit(:first_name,:last_name,:address1,:address2,:zipcode,:dob,:user_id)
    end
end

whogivesmore/app/helpers/account_informations_helper.rb
module AccountInformationsHelper
end

whogivesmore/app/views/account_informations/_form.html.erb
<%= form_for(@accountinformation) do |f| %>
<div class="field">
    <%= f.label :firstname%>
    <%= f.text_field :first_name %>
  </div>
<div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address1 %>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :zipcode %>
    <%= f.number_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :dob %>
    <%= f.date_field :dob %>
  </div>
  
  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

whogivesmore/app/views/account_informations/edit.html.erb
<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @accountinformation %> |
  <%= link_to "View All", account_informations_path %>
</p>

whogivesmore/app/views/account_informations/index.html.erb
<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>address1</th>
      <th>address2</th>
      <th>zipcode</th>
      <th>dob</th>
      <th>user_id</th>
    </tr>
  </thead>

  <tbody>
    <% @accountinformations.each do |account| %>
      <tr>
        <td><%= account.firstname %></td>
          <td><%= account.lastname %></td>
          <td><%= account.address1 %>
          <td><%= account.address2 %>
          <td><%= account.zipcode %>
          <td><%= account.dob %>
          <td><%= account.user_id%>
        <td><%= link_to 'Show',account_inofrmation %></td>
        <td><%= link_to 'Edit', edit_account_inormation_path(account_inofrmation) %></td>
        <td><%= link_to 'Destroy', account_inofrmation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Account info', new_account_information_path %>

whogivesmore/app/views/account_informations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', accountinformation: @accountinformation %>

<%= link_to 'Back', account_informations_path %>

whogivesmore/app/views/account_informations/show.html.erb
<p>
  <strong>FirstName:</strong>
  <%=h @accountinformation.first_name %>
</p>
<p>
  <strong>LastName:</strong>
  <%=h @accountinformation.last_name%>
</p>
<p>
  <strong>Adreess1</strong>
  <%=h @accountinformation.address1 %>
</p>
<p>
  <strong>Address2</strong>
  <%=h @accountinformation.address2 %>
</p>
<p>
  <strong>Zipcode:</strong>
  <%=h @accountinformation.zipcode %>
</p>
<p>
  <strong>dob</strong>
  <%=h @accountinformation.dob %>
</p>

<p>
  <strong>User_id:</strong>
  <%=h @accountinformation.user_id%>
</p>

<p>
  <%= link_to "Edit", edit_account_information_path(@accountinformation) %> |
  <%= link_to "Destroy", @accountinformation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", account_informations_path %>
</p>