whogivesmore/config/routes.rb
Rails.application.routes.draw do


  get 'mains/index'

  get 'mains/show'

  # get 'account_informations/index'

  # get 'account_informations/edit'

  # get 'account_informations/new'

  # get 'account_informations/show'

  # get 'donations/index'

  # get 'donations/new'

  # get 'donations/show'

  # get 'donations/edit'

  # get 'charties/index'

  # get 'charties/new'

  # get 'charties/show'

  # get 'charties/edit'

  # get 'competitions/index'

  # get 'competitions/show'

  # get 'competitions/edit'

  # get 'competitions/new'

  # get 'teams/index'

  # get 'teams/new'

  # get 'teams/show'

  # get 'teams/edit'

  # mount_devise_token_auth_for 'User', at: 'auth'
  
  # resources :users
  resources :teams
  resources :competitions
  resources :charties
  resources :donations
  resources :baskets

  # root 'home#index'
  resources :account_informations
  # devise_for :users

 devise_for :users, controllers: {
        sessions: 'users/sessions',       
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      } 
# as:user do
# devise_for :users, skip: [:registrations]
# as :user do
#   # get 'signin', to: 'devise/sessions#new', as: :new_user_session
#   # post 'signin', to: 'devise/sessions#create', as: :user_session

#   get 'sign_up',to: 'devise/registrations#new' ,as: :new_user_registration
#   get 'users/:id/edit',to: 'devise/registrations#edit', as: :edit_user_registration
#  patch 'users/:id',to: 'devise/registrations#update', as: :update_user_registration
#  put 'users/:id',to: 'devise/registrations#update'
#  delete 'users/:id',to: 'devise/registrations#destroy', as: :destroy_user_registration

#   # match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
# end
      
# devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #  namespace :users, :defaults => {:format => :json} do
  #   as :user do
  #     post   "/sign-in"       => "sessions#create"
  #     delete "/sign-out"      => "sessions#destroy"
  #   end
  # end
end

whogivesmore/app/models/competition.rb
class Competition < ApplicationRecord
  
  has_many :user_competitions
  has_many :users, through: :user_competitions

  validates :name ,:presence => true,
                   :uniqueness => true

  has_many :competition_teams
  has_many :teams ,through: :competition_teams

end

whogivesmore/app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
 before_action :set_competition, only: [:show, :edit, :update, :destroy]
# skip_before_action :require_login?
  def index
    @competitions =Competition.all
  end
  
  def show
  end

  def new
    @competition = Competition.new
  end

  def edit
  end

  def create
    @competition = Competition.new(competition_params)
    # binding..pry
    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'competition was successfully created.' }
        format.json { render json:{  status: :ok,data: @competition, }  }
      else
        format.html { render :new }
        format.json { render json:{status: :error,data: @competition.errors } }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'competition was successfully updated.' }
        format.json { render json:{status: :ok , data: @competition}   }
      else
        format.html { render :edit }
        format.json { render json:{status: :error,data: @competition.errors }}
      end
    end
  end

 
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { render json:{status: :delete }}
    end
  end

  private
    def set_competition
       @competition = Competition.where("id=?",params[:id]).first

      unless @competition.present? 
        render json:{ status: :error, data: "competition is not find" }

      end
    end
  
    def competition_params
      params.require(:competition).permit(:name,:end_date,:ranking_type,:no_end_date,:team_ids)
    end
end

whogivesmore/app/helpers/competitions_helper.rb
module CompetitionsHelper
end

whogivesmore/app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
<div class="field">
    <%= f.label :Name %>
    <%= f.text_field :name %>
  </div>
<div class="field">
    <%= f.label :ranking_type %>
    <%= f.text_field :ranking_type %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>
 <div class="field">
    <%= f.label :no_end_date %> <br />
    <%= f.check_box :no_end_date %> <br />
</div>
<div class="field">
  <%= f.collection_select :team_ids, Team.all, :id, :name %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

whogivesmore/app/views/competitions/edit.html.erb
<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @competition %> |
  <%= link_to "View All", competitions_path %>
</p>

whogivesmore/app/views/competitions/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>ranking_type</th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.name %></td>
          <td><%= competition.ranking_type %></td>
          <td><%= competition.end_date %>
          <td><%= competition.no_end_date %>
         <!--  <% @competitionteams.each# do |cteam| %>
          <% #if competition.id==cteam.competition_id %>
                    <td><%= cteam.team_id %>
           <% #end %>
           <% #end %> -->

        <td><%= link_to 'Show',competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New competition', new_competition_path %>

whogivesmore/app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Back', competitions_path %>

whogivesmore/app/views/competitions/show.html.erb
<p>
  <strong>Name:</strong>
  <%=h @competition.name%>
</p>
<p>
  <strong>ranking_type:</strong>
  <%=h @competition.ranking_type %>
</p>

<p>
  <strong>End_date:</strong>
  <%=h @competition.end_date%>
</p>

<p>
  <strong>No_end_date:</strong>
  <%=h @competition.no_end_date%>
</p>




<p>
  <%= link_to "Edit", edit_competition_path(@competition) %> |
  <%= link_to "Destroy", @competition, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", competitions_path %>
</p>